// <auto-generated />
using System;
using CarnetSante.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarnetSante.Data.Migrations
{
    [DbContext(typeof(CarnetSanteDbContext))]
    partial class CarnetSanteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CarnetSante.Core.Models.CertificatMedical", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("CirconstancesOrigine")
                    .HasColumnType("TEXT");

                b.Property<string>("CodeMedecin")
                    .HasColumnType("TEXT");

                b.Property<string>("Contenu")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DateCertificat")
                    .HasColumnType("TEXT");

                b.Property<string>("Etablissement")
                    .HasColumnType("TEXT");

                b.Property<string>("FichierNom")
                    .HasColumnType("TEXT");

                b.Property<string>("FichierPath")
                    .HasColumnType("TEXT");

                b.Property<long?>("FichierTaille")
                    .HasColumnType("INTEGER");

                b.Property<string>("FichierType")
                    .HasColumnType("TEXT");

                b.Property<bool?>("ImputabiliteService")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("INTEGER");

                b.Property<string>("MedecinSignataire")
                    .HasColumnType("TEXT");

                b.Property<string>("NumeroOrdre")
                    .HasColumnType("TEXT");

                b.Property<string>("Objet")
                    .HasColumnType("TEXT");

                b.Property<string>("Observations")
                    .HasColumnType("TEXT");

                b.Property<string>("OrigineBlessureOuMaladie")
                    .HasColumnType("TEXT");

                b.Property<int>("PatientId")
                    .HasColumnType("INTEGER");

                b.Property<string>("TypeCertificat")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("PatientId");

                b.ToTable("CertificatsMedicaux");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.Constante", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<decimal?>("Albumine")
                    .HasPrecision(5, 2)
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DateMesure")
                    .HasColumnType("TEXT");

                b.Property<int?>("FrequenceCardiaque")
                    .HasColumnType("INTEGER");

                b.Property<int?>("FrequenceRespiratoire")
                    .HasColumnType("INTEGER");

                b.Property<decimal?>("Glycemie")
                    .HasPrecision(5, 2)
                    .HasColumnType("TEXT");

                b.Property<decimal?>("IMC")
                    .HasPrecision(5, 2)
                    .HasColumnType("TEXT");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("INTEGER");

                b.Property<string>("MedecinMesureur")
                    .HasColumnType("TEXT");

                b.Property<string>("Observations")
                    .HasColumnType("TEXT");

                b.Property<int>("PatientId")
                    .HasColumnType("INTEGER");

                b.Property<decimal?>("PerimetreAbdominal")
                    .HasColumnType("TEXT");

                b.Property<decimal?>("PerimethreThoracique")
                    .HasColumnType("TEXT");

                b.Property<decimal?>("Poids")
                    .HasPrecision(5, 1)
                    .HasColumnType("TEXT");

                b.Property<decimal?>("Spo2")
                    .HasColumnType("TEXT");

                b.Property<decimal?>("Taille")
                    .HasPrecision(5, 1)
                    .HasColumnType("TEXT");

                b.Property<int?>("TensionDiastolique")
                    .HasColumnType("INTEGER");

                b.Property<int?>("TensionSystolique")
                    .HasColumnType("INTEGER");

                b.Property<decimal?>("Temperature")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasColumnType("TEXT");

                b.Property<string>("UnitéGlycemie")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("PatientId");

                b.ToTable("Constantes");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.ContactUrgence", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Adresse")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<int>("EtatCivilId")
                    .HasColumnType("INTEGER");

                b.Property<bool>("EstPrioritaire")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("INTEGER");

                b.Property<string>("LienParente")
                    .HasColumnType("TEXT");

                b.Property<string>("NomComplet")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("Telephone")
                    .HasColumnType("TEXT");

                b.Property<string>("TelephoneAlternatif")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("EtatCivilId");

                b.ToTable("ContactsUrgence");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.ControleFInService", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int>("AptitudeRejoindreForyer")
                    .HasConversion<int>()
                    .HasColumnType("INTEGER");

                b.Property<string>("CodeMedecin")
                    .HasColumnType("TEXT");

                b.Property<string>("ConditionsRejoindreForyer")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DateControle")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("DateFinService")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("DateRadiation")
                    .HasColumnType("TEXT");

                b.Property<string>("DiagnosticsFinaux")
                    .HasColumnType("TEXT");

                b.Property<string>("EtatDeSante")
                    .HasColumnType("TEXT");

                b.Property<string>("ExamenFinal")
                    .HasColumnType("TEXT");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("INTEGER");

                b.Property<string>("MedecinSignataire")
                    .HasColumnType("TEXT");

                b.Property<string>("MotifFinService")
                    .HasColumnType("TEXT");

                b.Property<string>("NumeroDecisionRadiation")
                    .HasColumnType("TEXT");

                b.Property<string>("Observations")
                    .HasColumnType("TEXT");

                b.Property<int>("PatientId")
                    .HasColumnType("INTEGER");

                b.Property<string>("RecapitulatifIndisponibilites")
                    .HasColumnType("TEXT");

                b.Property<string>("RecapitulatifInterventions")
                    .HasColumnType("TEXT");

                b.Property<string>("RecapitulatifPathologies")
                    .HasColumnType("TEXT");

                b.Property<string>("RecommandationsMedicales")
                    .HasColumnType("TEXT");

                b.Property<string>("SignatureMedecin")
                    .HasColumnType("TEXT");

                b.Property<int?>("TotalJoursIndisponibilite")
                    .HasColumnType("INTEGER");

                b.Property<string>("TraitementsDeLongDuree")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("PatientId")
                    .IsUnique();

                b.ToTable("ControlesFinService");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.DecisionReforme", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("AffectionsAssociees")
                    .HasColumnType("TEXT");

                b.Property<string>("AffectionsPrincipales")
                    .HasColumnType("TEXT");

                b.Property<string>("CodeCIM10")
                    .HasColumnType("TEXT");

                b.Property<string>("CompositionCommission")
                    .HasColumnType("TEXT");

                b.Property<string>("ConditionsReengagement")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DateDecision")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("DateEffet")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("DateReunionCommission")
                    .HasColumnType("TEXT");

                b.Property<int>("Decision")
                    .HasConversion<int>()
                    .HasColumnType("INTEGER");

                b.Property<string>("Diagnostic")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("INTEGER");

                b.Property<string>("LieuCommission")
                    .HasColumnType("TEXT");

                b.Property<string>("MotifDecision")
                    .HasColumnType("TEXT");

                b.Property<string>("NumeroDecision")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Observations")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("PatientId")
                    .HasColumnType("INTEGER");

                b.Property<bool>("PensionAttribuee")
                    .HasColumnType("INTEGER");

                b.Property<string>("TauxInvalidite")
                    .HasColumnType("TEXT");

                b.Property<decimal?>("TauxPension")
                    .HasColumnType("TEXT");

                b.Property<string>("TypePension")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("PatientId");

                b.ToTable("DecisionsReforme");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.EtatCivil", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Adresse")
                    .HasColumnType("TEXT");

                b.Property<string>("Corps")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DateNaissance")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("DateRecrutement")
                    .HasColumnType("TEXT");

                b.Property<string>("Email")
                    .HasColumnType("TEXT");

                b.Property<string>("EmpreintesImagePath")
                    .HasColumnType("TEXT");

                b.Property<string>("EmpreintesNotes")
                    .HasColumnType("TEXT");

                b.Property<string>("Fonction")
                    .HasColumnType("TEXT");

                b.Property<string>("Grade")
                    .HasColumnType("TEXT");

                b.Property<int>("GroupeSanguin")
                    .HasConversion<int>()
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("INTEGER");

                b.Property<string>("LieuNaissance")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("Nationalite")
                    .HasColumnType("TEXT");

                b.Property<string>("Nom")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("NomMere")
                    .HasColumnType("TEXT");

                b.Property<string>("NomPere")
                    .HasColumnType("TEXT");

                b.Property<int?>("NombreEnfants")
                    .HasColumnType("INTEGER");

                b.Property<string>("NumeroCNI")
                    .HasColumnType("TEXT");

                b.Property<string>("NumeroMatricule")
                    .HasColumnType("TEXT");

                b.Property<string>("NumeroPasseport")
                    .HasColumnType("TEXT");

                b.Property<int>("PatientId")
                    .HasColumnType("INTEGER");

                b.Property<string>("PaysNaissance")
                    .HasColumnType("TEXT");

                b.Property<string>("Prenoms")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("PrenomsMere")
                    .HasColumnType("TEXT");

                b.Property<string>("PrenomsPere")
                    .HasColumnType("TEXT");

                b.Property<string>("ProfessionMere")
                    .HasColumnType("TEXT");

                b.Property<string>("ProfessionPere")
                    .HasColumnType("TEXT");

                b.Property<int>("Sexe")
                    .HasConversion<int>()
                    .HasColumnType("INTEGER");

                b.Property<string>("SituationMatrimoniale")
                    .HasColumnType("TEXT");

                b.Property<string>("Telephone")
                    .HasColumnType("TEXT");

                b.Property<string>("Unite")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("PatientId")
                    .IsUnique();

                b.ToTable("EtatsCivils");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.ExamenIncorporation", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("AllergiesConnues")
                    .HasColumnType("TEXT");

                b.Property<string>("AntecedentsCollateraux")
                    .HasColumnType("TEXT");

                b.Property<string>("AntecedentsHeredita")
                    .HasColumnType("TEXT");

                b.Property<string>("AntecedentsPersonnels")
                    .HasColumnType("TEXT");

                b.Property<string>("AppareilCirculatoire")
                    .HasColumnType("TEXT");

                b.Property<string>("AppareilDigestif")
                    .HasColumnType("TEXT");

                b.Property<string>("AppareilGenitourinaire")
                    .HasColumnType("TEXT");

                b.Property<string>("AppareilRespiratoire")
                    .HasColumnType("TEXT");

                b.Property<int>("AptitudeMedicale")
                    .HasConversion<int>()
                    .HasColumnType("INTEGER");

                b.Property<string>("AuditionODVoixChuchote")
                    .HasColumnType("TEXT");

                b.Property<string>("AuditionODVoixHaute")
                    .HasColumnType("TEXT");

                b.Property<string>("AuditionOGVoixChuchote")
                    .HasColumnType("TEXT");

                b.Property<string>("AuditionOGVoixHaute")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DateExamen")
                    .HasColumnType("TEXT");

                b.Property<string>("Denture")
                    .HasColumnType("TEXT");

                b.Property<decimal?>("EcartPupillaire")
                    .HasColumnType("TEXT");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("INTEGER");

                b.Property<string>("MedecinExaminateur")
                    .HasColumnType("TEXT");

                b.Property<string>("MentionsMedicalesSpeciales")
                    .HasColumnType("TEXT");

                b.Property<string>("ObservationsAuditives")
                    .HasColumnType("TEXT");

                b.Property<string>("ObservationsSensChromatique")
                    .HasColumnType("TEXT");

                b.Property<string>("ObservationsVisuelles")
                    .HasColumnType("TEXT");

                b.Property<string>("Observations")
                    .HasColumnType("TEXT");

                b.Property<int>("PatientId")
                    .HasColumnType("INTEGER");

                b.Property<string>("PeauAnnexes")
                    .HasColumnType("TEXT");

                b.Property<string>("RestrictionsActivite")
                    .HasColumnType("TEXT");

                b.Property<bool?>("SensChromatique")
                    .HasColumnType("INTEGER");

                b.Property<string>("Signature")
                    .HasColumnType("TEXT");

                b.Property<string>("SystemeEndocrinien")
                    .HasColumnType("TEXT");

                b.Property<string>("SystemeNerveux")
                    .HasColumnType("TEXT");

                b.Property<string>("SystemeOsteoarticulaire")
                    .HasColumnType("TEXT");

                b.Property<string>("TraitementsEnCours")
                    .HasColumnType("TEXT");

                b.Property<string>("TypeCorrectionOD")
                    .HasColumnType("TEXT");

                b.Property<string>("TypeCorrectionOG")
                    .HasColumnType("TEXT");

                b.Property<string>("TypeDaltonisme")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasColumnType("TEXT");

                b.Property<decimal?>("VisionODAvecCorrection")
                    .HasColumnType("TEXT");

                b.Property<decimal?>("VisionODSansCorrection")
                    .HasColumnType("TEXT");

                b.Property<decimal?>("VisionOGAvecCorrection")
                    .HasColumnType("TEXT");

                b.Property<decimal?>("VisionOGSansCorrection")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("PatientId")
                    .IsUnique();

                b.ToTable("ExamensIncorporation");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.Indisponibilite", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("CodeCIM10")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DateDebut")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("DateFin")
                    .HasColumnType("TEXT");

                b.Property<string>("Diagnostic")
                    .HasColumnType("TEXT");

                b.Property<int>("DureePrescrite")
                    .HasColumnType("INTEGER");

                b.Property<int?>("DureeReelle")
                    .HasColumnType("INTEGER");

                b.Property<string>("EtatDepart")
                    .HasColumnType("TEXT");

                b.Property<string>("EtatRetour")
                    .HasColumnType("TEXT");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("INTEGER");

                b.Property<string>("LieuSejour")
                    .HasColumnType("TEXT");

                b.Property<string>("MedecinPrescripteur")
                    .HasColumnType("TEXT");

                b.Property<string>("Motif")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<string>("Observations")
                    .HasColumnType("TEXT");

                b.Property<int>("PatientId")
                    .HasColumnType("INTEGER");

                b.Property<string>("SignatureMedecin")
                    .HasColumnType("TEXT");

                b.Property<int>("Statut")
                    .HasConversion<int>()
                    .HasColumnType("INTEGER");

                b.Property<string>("TypeSejour")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("PatientId");

                b.ToTable("Indisponibilites");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.JournalAudit", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("AdresseIP")
                    .HasColumnType("TEXT");

                b.Property<string>("AnciennesValeurs")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DateAction")
                    .HasColumnType("TEXT");

                b.Property<string>("Description")
                    .HasColumnType("TEXT");

                b.Property<string>("EntiteAffectee")
                    .HasColumnType("TEXT");

                b.Property<int?>("IdEntiteAffectee")
                    .HasColumnType("INTEGER");

                b.Property<string>("LoginUtilisateur")
                    .HasColumnType("TEXT");

                b.Property<string>("NomMachine")
                    .HasColumnType("TEXT");

                b.Property<string>("NouvellesValeurs")
                    .HasColumnType("TEXT");

                b.Property<int?>("PatientId")
                    .HasColumnType("INTEGER");

                b.Property<int>("TypeAction")
                    .HasConversion<int>()
                    .HasColumnType("INTEGER");

                b.Property<int?>("UtilisateurId")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.HasIndex("UtilisateurId");

                b.ToTable("JournalAudits");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.OperationMedicale", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ChirurgienPrincipal")
                    .HasColumnType("TEXT");

                b.Property<string>("CodeMedecin")
                    .HasColumnType("TEXT");

                b.Property<string>("Complications")
                    .HasColumnType("TEXT");

                b.Property<string>("CompteRenduPath")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("DateAdmission")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DateOperation")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("DateSortie")
                    .HasColumnType("TEXT");

                b.Property<string>("DescriptionIntervention")
                    .HasColumnType("TEXT");

                b.Property<string>("Diagnostic")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<int?>("DureeSejour")
                    .HasColumnType("INTEGER");

                b.Property<string>("EquipeMedicale")
                    .HasColumnType("TEXT");

                b.Property<string>("EtatApres")
                    .HasColumnType("TEXT");

                b.Property<string>("EtatAvant")
                    .HasColumnType("TEXT");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("INTEGER");

                b.Property<string>("LieuSejour")
                    .HasColumnType("TEXT");

                b.Property<string>("Observations")
                    .HasColumnType("TEXT");

                b.Property<int>("PatientId")
                    .HasColumnType("INTEGER");

                b.Property<string>("SignatureMedecin")
                    .HasColumnType("TEXT");

                b.Property<string>("SuitesDonnees")
                    .HasColumnType("TEXT");

                b.Property<int>("TypeIntervention")
                    .HasConversion<int>()
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("PatientId");

                b.ToTable("OperationsMedicales");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.Patient", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("CreatedBy")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("INTEGER");

                b.Property<string>("NumeroCarnet")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("TEXT");

                b.Property<string>("PhotoPath")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("NumeroCarnet")
                    .IsUnique();

                b.ToTable("Patients");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.Utilisateur", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("BloquéJusquau")
                    .HasColumnType("TEXT");

                b.Property<string>("CodeMedecin")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("DerniereConnexion")
                    .HasColumnType("TEXT");

                b.Property<string>("Email")
                    .HasColumnType("TEXT");

                b.Property<bool>("EstActif")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("INTEGER");

                b.Property<string>("Login")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<string>("MotDePasseHash")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Nom")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("Prenom")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<int>("Role")
                    .HasConversion<int>()
                    .HasColumnType("INTEGER");

                b.Property<string>("Specialite")
                    .HasColumnType("TEXT");

                b.Property<int>("TentativesEchec")
                    .HasColumnType("INTEGER");

                b.Property<string>("Telephone")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Login")
                    .IsUnique();

                b.ToTable("Utilisateurs");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Login = "admin",
                        MotDePasseHash = "$2a$11$hFld1/jMKcREPGqVYYjde.RM5HWc9SDBIXRSLTWZbq0RBPdxhLOle",
                        Nom = "Administrateur",
                        Prenom = "Système",
                        Role = 1,
                        EstActif = true,
                        TentativesEchec = 0,
                        CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc),
                        IsDeleted = false
                    });
            });

            modelBuilder.Entity("CarnetSante.Core.Models.Vaccination", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("CodeMedecin")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DateVaccination")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("DateExpiration")
                    .HasColumnType("TEXT");

                b.Property<string>("Etablissement")
                    .HasColumnType("TEXT");

                b.Property<bool>("EstValide")
                    .HasColumnType("INTEGER");

                b.Property<string>("FabricantVaccin")
                    .HasColumnType("TEXT");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("INTEGER");

                b.Property<string>("MedecinVaccinateur")
                    .HasColumnType("TEXT");

                b.Property<string>("NomVaccin")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("NumeroLot")
                    .HasColumnType("TEXT");

                b.Property<int>("NumeroDose")
                    .HasColumnType("INTEGER");

                b.Property<string>("Observations")
                    .HasColumnType("TEXT");

                b.Property<int>("PatientId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("ProchaineInjectionPrevue")
                    .HasColumnType("TEXT");

                b.Property<decimal?>("QuantitéDose")
                    .HasColumnType("TEXT");

                b.Property<string>("ReactionPostVaccinale")
                    .HasColumnType("TEXT");

                b.Property<string>("Reference")
                    .HasColumnType("TEXT");

                b.Property<string>("SiteInjection")
                    .HasColumnType("TEXT");

                b.Property<string>("TypeDose")
                    .HasColumnType("TEXT");

                b.Property<int>("TypeVaccin")
                    .HasConversion<int>()
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasColumnType("TEXT");

                b.Property<string>("VoieAdministration")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("PatientId");

                b.ToTable("Vaccinations");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.VisiteSanitaire", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("AptitudeConclusionVisite")
                    .HasColumnType("TEXT");

                b.Property<string>("CodeMedecin")
                    .HasColumnType("TEXT");

                b.Property<string>("CreatedBy")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("DateVisite")
                    .HasColumnType("TEXT");

                b.Property<string>("DiagnosticsRetenus")
                    .HasColumnType("TEXT");

                b.Property<string>("EntiteMedicale")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("ExamensPrescrits")
                    .HasColumnType("TEXT");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("INTEGER");

                b.Property<string>("NomMedecin")
                    .HasColumnType("TEXT");

                b.Property<string>("Observations")
                    .HasColumnType("TEXT");

                b.Property<int>("PatientId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("ProchainContrôle")
                    .HasColumnType("TEXT");

                b.Property<string>("ResultatsVisite")
                    .HasColumnType("TEXT");

                b.Property<string>("SignatureMedecin")
                    .HasColumnType("TEXT");

                b.Property<string>("TraitementsPrescrits")
                    .HasColumnType("TEXT");

                b.Property<string>("TypeVisite")
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("UpdatedBy")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("PatientId");

                b.ToTable("VisitesSanitaires");
            });

            // ── Relations ───────────────────────────────────────────────

            modelBuilder.Entity("CarnetSante.Core.Models.CertificatMedical", b =>
            {
                b.HasOne("CarnetSante.Core.Models.Patient", "Patient")
                    .WithMany("CertificatsMedicaux")
                    .HasForeignKey("PatientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Patient");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.Constante", b =>
            {
                b.HasOne("CarnetSante.Core.Models.Patient", "Patient")
                    .WithMany("Constantes")
                    .HasForeignKey("PatientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Patient");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.ContactUrgence", b =>
            {
                b.HasOne("CarnetSante.Core.Models.EtatCivil", "EtatCivil")
                    .WithMany("ContactsUrgence")
                    .HasForeignKey("EtatCivilId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("EtatCivil");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.ControleFInService", b =>
            {
                b.HasOne("CarnetSante.Core.Models.Patient", "Patient")
                    .WithOne("ControleFinService")
                    .HasForeignKey("CarnetSante.Core.Models.ControleFInService", "PatientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Patient");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.DecisionReforme", b =>
            {
                b.HasOne("CarnetSante.Core.Models.Patient", "Patient")
                    .WithMany("DecisionsReforme")
                    .HasForeignKey("PatientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Patient");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.EtatCivil", b =>
            {
                b.HasOne("CarnetSante.Core.Models.Patient", "Patient")
                    .WithOne("EtatCivil")
                    .HasForeignKey("CarnetSante.Core.Models.EtatCivil", "PatientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Patient");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.ExamenIncorporation", b =>
            {
                b.HasOne("CarnetSante.Core.Models.Patient", "Patient")
                    .WithOne("ExamenIncorporation")
                    .HasForeignKey("CarnetSante.Core.Models.ExamenIncorporation", "PatientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Patient");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.Indisponibilite", b =>
            {
                b.HasOne("CarnetSante.Core.Models.Patient", "Patient")
                    .WithMany("Indisponibilites")
                    .HasForeignKey("PatientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Patient");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.JournalAudit", b =>
            {
                b.HasOne("CarnetSante.Core.Models.Utilisateur", "Utilisateur")
                    .WithMany("JournalAudits")
                    .HasForeignKey("UtilisateurId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.Navigation("Utilisateur");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.OperationMedicale", b =>
            {
                b.HasOne("CarnetSante.Core.Models.Patient", "Patient")
                    .WithMany("OperationsMedicales")
                    .HasForeignKey("PatientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Patient");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.Vaccination", b =>
            {
                b.HasOne("CarnetSante.Core.Models.Patient", "Patient")
                    .WithMany("Vaccinations")
                    .HasForeignKey("PatientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Patient");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.VisiteSanitaire", b =>
            {
                b.HasOne("CarnetSante.Core.Models.Patient", "Patient")
                    .WithMany("VisitesSanitaires")
                    .HasForeignKey("PatientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Patient");
            });

            // ── Navigations inverses ────────────────────────────────────

            modelBuilder.Entity("CarnetSante.Core.Models.EtatCivil", b =>
            {
                b.Navigation("ContactsUrgence");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.Patient", b =>
            {
                b.Navigation("CertificatsMedicaux");
                b.Navigation("Constantes");
                b.Navigation("ControleFinService");
                b.Navigation("DecisionsReforme");
                b.Navigation("EtatCivil");
                b.Navigation("ExamenIncorporation");
                b.Navigation("Indisponibilites");
                b.Navigation("OperationsMedicales");
                b.Navigation("Vaccinations");
                b.Navigation("VisitesSanitaires");
            });

            modelBuilder.Entity("CarnetSante.Core.Models.Utilisateur", b =>
            {
                b.Navigation("JournalAudits");
            });
#pragma warning restore 612, 618
        }
    }
}
