<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CarnetSante.WPF</RootNamespace>
    <AssemblyName>CarnetSante</AssemblyName>
    <Platforms>x64</Platforms>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <LangVersion>12</LangVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CarnetSante.Data\CarnetSante.Data.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.WPF" Version="1.1.77" />
    <PackageReference Include="PdfSharpCore" Version="1.3.65" />
  </ItemGroup>
</Project>
